/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DatabaseConnection;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Osusara
 */
public class GRNList extends javax.swing.JFrame {

    /**
     * Creates new form GRNList
     */
    public GRNList() {
        initComponents();
        grnDataLoad();
        
        grnSearchTextField.setForeground(Color.gray);
        grnSearchTextField.setText("Search Date");
    }

    public void grnDataLoad() {
        DefaultTableModel dtm = (DefaultTableModel) grnTable.getModel();
        try {
            ResultSet rs = DatabaseConnection.getConnection().executeQuery("SELECT * FROM grn");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("grn_id"));
                v.add(rs.getString("date"));
                v.add(rs.getString("item_id"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("total"));
                v.add(rs.getString("supplier_id"));
                v.add(rs.getString("user_id"));
                dtm.addRow(v);
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grnTable = new javax.swing.JTable();
        grnSearchTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        grnTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        grnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN ID", "Date", "Item", "Quantity", "Total", "Supplier", "User"
            }
        ));
        grnTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jScrollPane1.setViewportView(grnTable);

        grnSearchTextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        grnSearchTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        grnSearchTextField.setText("Search Date");
        grnSearchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        grnSearchTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        grnSearchTextField.setSelectionColor(new java.awt.Color(102, 153, 255));
        grnSearchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                grnSearchTextFieldFocusLost(evt);
            }
        });
        grnSearchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grnSearchTextFieldMouseClicked(evt);
            }
        });
        grnSearchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                grnSearchTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(grnSearchTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grnSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void grnSearchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grnSearchTextFieldFocusLost
        if (grnSearchTextField.getText().isEmpty()) {
            grnSearchTextField.setForeground(Color.gray);
            grnSearchTextField.setText("Search Date");
        }
    }//GEN-LAST:event_grnSearchTextFieldFocusLost

    private void grnSearchTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grnSearchTextFieldMouseClicked
        grnSearchTextField.setBorder(BorderFactory.createLineBorder(Color.decode("#999999")));
        if (grnSearchTextField.getForeground() == Color.gray) {
            grnSearchTextField.setText(null);
        }
    }//GEN-LAST:event_grnSearchTextFieldMouseClicked

    private void grnSearchTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnSearchTextFieldKeyTyped
        if (grnSearchTextField.getForeground() == Color.gray) {
            grnSearchTextField.setText(null);
        }
        grnSearchTextField.setForeground(Color.black);

        DefaultTableModel dtm = (DefaultTableModel) grnTable.getModel();
        String s = grnSearchTextField.getText();
        try {
            ResultSet rs = DatabaseConnection.getConnection().executeQuery("SELECT * FROM grn WHERE date LIKE '%" + s + "%'");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("grn_id"));
                v.add(rs.getString("date"));
                v.add(rs.getString("item_id"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("total"));
                v.add(rs.getString("supplier_id"));
                v.add(rs.getString("user_id"));
                dtm.addRow(v);
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_grnSearchTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRNList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRNList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRNList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRNList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GRNList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField grnSearchTextField;
    private javax.swing.JTable grnTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
